### ISSUE TITLE
Runtime crash "No static method  blabla"

### ISSUE THREAD

**Issue by jscti** [MFlisar/ComposePreferences#10]
Hi there

Finished migrating to kotlin-multiplatform. All went smooth, good job !

Just today, when upgrading to 2.1.3, I got a crash on the NumberPreference :  
```
java.lang.NoSuchMethodError: No static method options$default(Lcom/michaelflisar/composedialogs/core/DialogDefaults;ZZZILjava/lang/Object;)Lcom/michaelflisar/composedialogs/core/Options; in class Lcom/michaelflisar/composedialogs/core/DialogDefaults; or its super classes (declaration of 'com.michaelflisar.composedialogs.core.DialogDefaults' appears in /data/app/~~fhN4S9ANfepd-dNfk7QAvw==/com.xxxxxxxxx-yOsAnt_LBa_kV8D6uq5GtQ==/base.apk!classes18.dex)
	at com.michaelflisar.composedialogs.dialogs.number.DialogNumberPickerKt.DialogNumberPicker(DialogNumberPicker.kt:77)
	at com.michaelflisar.composepreferences.screen.number.PreferenceNumberDefaults.dialog(PreferenceNumber.kt:276)
	at com.michaelflisar.composepreferences.screen.number.PreferenceNumberKt$PreferenceNumber$6.invoke(PreferenceNumber.kt:142)
	at com.michaelflisar.composepreferences.screen.number.PreferenceNumberKt$PreferenceNumber$6.invoke(PreferenceNumber.kt:141)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at com.michaelflisar.composepreferences.core.composables.BasePreferenceDialogKt.BasePreferenceDialog(BasePreferenceDialog.kt:44)
	at com.michaelflisar.composepreferences.screen.number.PreferenceNumberKt.PreferenceNumber(PreferenceNumber.kt:158)
	at com.michaelflisar.composepreferences.screen.number.PreferenceNumberKt.PreferenceNumber$lambda$7(Unknown Source:52)
	at com.michaelflisar.composepreferences.screen.number.PreferenceNumberKt.$r8$lambda$EVFWfeWzWuEzV0qqH0Oy62VHQlg(Unknown Source:0)
	at com.michaelflisar.composepreferences.screen.number.PreferenceNumberKt$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
```

Using : composeBom = "2025.03.00"

Not reproducting on 2.1.2. All other preference dialogs I use are OK
Let me know if you need any other info

**Comment by MFlisar** [comment]
Version 1.1.1 should solve that. Seems like my changes in the dialog library have not been binary compatible although I thought so... I updated the dependency and made a new release - let me know if this solves the problem.

New version should be available in less than an hour...

**Comment by jscti** [comment]
Yep working thanks for the quick fix.
But @MFlisar it's the second time now for this silent/runtyme bug. It's quite dangerous.
Isn't there a way to detect/block/error it at compile time ?
Or during automated tests and ... here I see no test at all on this lib Outch 

I'll have to configure some espresso test to ensure all is working fine on my app

**Comment by MFlisar** [comment]
I added a binary compatibility library to my project(s) but I'm still learing to use it... The problem was not in this library but in the last update of ComposeDialogs. When you update the ComposeDialogs versions gradle will automatically use the it in your project and will also use it for this library (transitive dependencies)...

This time code was 100% compatible (I did not change any code in this library for the last update). When making an update to ComposeDialogs I normally check this library as well - it compiled without problems so I assumed it's compatible with the update...

**Comment by jscti** [comment]
I totally understand that shit happens, no problem with that. Dependencies issues are common ;)
It's just the fact nothing blocks this type of problem before runtime that I think is wrong/dangerous. I don't get why gradle compile (but I have 0 experience with binary libs)
